name: Create a script.sh files with workflow dispatch inputs interpreted variables and run the script.
on: 
  workflow_dispatch:
    inputs:
      variable1:
        description: 'variable1-description'     
        required: true
        default: 'value1'
      variable2:
        description: 'variable2-description'     
        required: true
        default: 'value2'

jobs:
  createscriptandruntheinputs:
    runs-on: ubuntu-latest
    steps:        
    - name: Create script.sh and run it.
      run: |
        cat << EOF > myscript.sh
        echo "Variable 1's value is : ${{ github.event.inputs.variable1 }}"
        echo "Variable 2's value is : ${{ github.event.inputs.variable2 }}"
        EOF
        chmod +x myscript.sh && ./myscript.sh


