on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    environment: testenv
    runs-on: ubuntu-latest
    steps:

        
    - run: |
        cat >myscript '<< EOF
echo "Log level: ${{ github.event.inputs.logLevel }}"
echo "Tags: ${{ github.event.inputs.tags }}" 
EOF
bash myscript

