on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    environment: testenv
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        MYSECRET: ${{ secrets.MYSECRET }}
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        echo "$MYSECRET"

